$schema: http://json-schema.org/draft-07/schema#
title: Chapel MP3 Metadata Schema
description: JSON Schema for chapel MP3 metadata YAML format used for audio files including music and podcasts
type: object
properties:
  title:
    type: string
    description: Track or episode title. For podcasts, this is the episode title.
  subtitle:
    type: string
    description: Subtitle or description refinement. Commonly used in podcasts for episode descriptions or additional title information.
  artist:
    type: string
    description: Artist or performer name. For podcasts, this is typically the host or creator name.
  album:
    type: string
    description: Album or series name. For podcasts, this is the podcast series name.
  albumArtist:
    type: string
    description: Album artist or main performer. For podcasts, this is the main podcast creator or network.
  grouping:
    type: string
    description: Content group description. Used to group related tracks together, such as movements of a work or episodes in a series/season.
  date:
    type: string
    pattern: '^\d{4}(-\d{2}(-\d{2}(T\d{2}(:\d{2}(:\d{2})?)?)?)?)?$'
    description: Recording time in ID3v2 timestamp format (subset of ISO 8601). Supports yyyy, yyyy-MM, yyyy-MM-dd, yyyy-MM-ddTHH, yyyy-MM-ddTHH:mm, yyyy-MM-ddTHH:mm:ss. All timestamps are UTC. For podcasts, this is the episode recording or publication date.
  track:
    type: string
    pattern: '^\d+(/\d+)?$'
    description: Track number in ID3v2 format. Can be "3" or "3/10" (current/total). For podcasts, this can represent the episode number.
  disc:
    type: string
    pattern: '^\d+(/\d+)?$'
    description: Disc number in ID3v2 format. Can be "1" or "1/2" (current/total). For multi-disc releases. Less commonly used for podcasts.
  genre:
    type: string
    description: Musical genre or category. For podcasts, use "Podcast" or more specific categories like "Technology", "News", "Comedy", etc.
  comment:
    type: string
    description: Additional comments or notes about the track. For podcasts, this can include episode notes or descriptions.
  composer:
    type: string
    description: Composer of the music. For podcasts, this might be used for theme music composer or less commonly for content creator.
  publisher:
    type: string
    description: Record label or publisher. For podcasts, this is the podcast network or publishing platform.
  copyright:
    type: string
    description: Copyright message. Contains copyright information for the audio content.
  language:
    type: string
    description: Language code(s) for the audio content. ISO 639-2 language code (e.g., "eng" for English, "jpn" for Japanese).
  bpm:
    type: integer
    minimum: 1
    description: Beats per minute for musical content. Not typically used for podcasts.
  artwork:
    type: string
    description: Artwork as data URI (data:image/jpeg;base64,...), HTTP/HTTPS URL, or file path (absolute or relative). For podcasts, this is the episode or series artwork/cover image.
  lyrics:
    type: string
    description: Song lyrics or transcript. For podcasts, this can contain the episode transcript.
  chapters:
    type: array
    description: Chapter markers for navigation within the audio content. Particularly useful for podcasts to mark different topics or segments.
    items:
      type: string
      pattern: '^(\d+:\d{2}(:\d{2})?(\.\d{1,3})?)\s+.+$'
      description: 'Chapter in WebVTT format: "M:SS Title", "H:MM:SS Title", or with milliseconds "M:SS.mmm Title". Example: "5:30 Introduction", "15:45.500 Main Topic"'
additionalProperties: false
